java_library(
  name = 'all',
  srcs = glob(['**/*.java']),
  extra_arguments = [
    '-Xlint:all',
    '-verbose',
  ],
  visibility = [
    '//src/test/java/com/tejohnso:test',
  ],
)
java_binary(
  name = 'HelloWorld',
  main_class = 'com.tejohnso.HelloWorld',
  deps = [
    ':all'
  ],
)
